# Site settings
title: William Rondón Demo's
email: 
description: > # this means to ignore newlines until "baseurl:"
 Site to show examples of code for Android based mobile applications.
 by William Rondon.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wrondon
github_username:  wrondon

# Build settings
markdown: kramdown
